version: '3.9'

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_fastapi
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: >
      redis-server --save 5 1 --databases 2 --protected-mode no
      --dir /data --dbfilename redis.rdb

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
    env_file:
      - .env.docker
    volumes:
      - db_data:/app/db

volumes:
    redis_data:
      driver: local
    db_data:
      driver: local
